const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),D=require('../assets/dashboard-view.js'),N=require('../assets/nwp.js'),O=require('../assets/operations-core.js'),L=require('../assets/live-core.js'),sites=require('../data/sites.json');
function forecast(group=0){return {group,version:N.currentVersion(),retrievedAt:new Date().toISOString(),windows:Object.fromEntries([3,7].map(h=>[h,{start:'2026-09-30',end:h===3?'2026-10-02':'2026-10-06',probabilities:{rain:.6,heat:.1,dry:.1,compound:.1},levels:{rain:'red',heat:'green',dry:'green',compound:'green'}}]))};}
test('city conclusions count only the named highest severity and disclose other hazards',()=>{const a=forecast(),b=forecast(1);b.windows[7].levels.rain='yellow';b.windows[7].probabilities.rain=.3;b.windows[7].levels.dry='yellow';b.windows[7].probabilities.dry=.8;const s=D.citySummary([{n:a,current:true},{n:b,current:true}],7);assert.equal(s.level,'Red');assert.equal(s.line,'7-day heavy rain: Red in 1/2 groups (60–60%)');assert.ok(s.detail.includes('Yellow in 1 group'));assert.ok(s.detail.includes('low rainfall: Alert'));assert.equal(D.highest(b,7),'Yellow');});
test('single-level non-rain summaries and Clear states do not manufacture rain warnings',()=>{const n=forecast();n.windows[7].levels={rain:'green',heat:'green',dry:'yellow',compound:'green'};assert.equal(D.highest(n,7),'Alert');assert.ok(D.citySummary([{n,current:true}],7).line.includes('low rainfall: Alert in 1/1'));n.windows[7].levels.dry='green';assert.equal(D.highest(n,7),'Clear');assert.ok(D.citySummary([{n,current:true}],7).detail.includes('All four hazards'));});
test('stale cached runs remain visible but cannot receive a current map colour',()=>{const n=forecast();const s=D.citySummary([{n,current:false},{n:null,current:false}],7);assert.equal(s.level,'Unknown');assert.ok(s.line.startsWith('Saved run'));assert.ok(s.detail.includes('not current'));assert.equal(D.highest(n,7,false),'Unknown');n.windows[7].probabilities.dry=null;assert.equal(D.highest(n,7),'Unknown');});
test('map contains all 21 labelled inspect links, preserved group IDs and colour levels',()=>{const reps=[...new Map(sites.map(s=>[s.group,s])).values()],groups=reps.map(site=>({site,n:forecast(site.group),current:true,coordinate:[N.data.centroids[site.group].lon,N.data.centroids[site.group].lat]}));const html=D.mapSvg({features:[]},groups,7);assert.equal((html.match(/data-field="open-group"/g)||[]).length,21);assert.equal((html.match(/class="group-dot"/g)||[]).length,21);assert.ok(html.includes('viewBox="0 0 360 440"'));for(const g of groups)assert.ok(html.includes(`group ${g.site.group+1}: Red`));const filtered=D.mapSvg({features:[]},groups,7,'Coimbra');assert.equal((filtered.match(/tabindex="0"/g)||[]).length,5);});
test('archived probability changes identify different date windows and exclude different models',()=>{const a=forecast(),b=forecast();a.windows[7].probabilities.rain=.41;assert.ok(D.change(b,a,7).includes('41% → 60%'));a.windows[7].start='2026-09-29';assert.ok(D.change(b,a,7).includes('different forecast dates'));a.version='old';assert.equal(D.change(b,a,7),null);});
async function boot({cached=[],online=true,page="dashboard",rain=2,heat=24}={}){
 const nodes={app:{innerHTML:''},toast:{textContent:'',classList:{add(){},remove(){}}}},store={'streamsignal.groupForecasts.v6':JSON.stringify(cached)},calls=[];
 const document={documentElement:{},getElementById:id=>nodes[id]||{},addEventListener(){},createElement:()=>({}),head:{append(script){script.onload();}}};
 const window={StreamLive:L,StreamNWP:N,StreamOps:O,StreamDashboard:D,StreamBulletin:require('../assets/bulletin.js'),StreamLanguages:{en:{name:'English'}},STREAM_MAP:{features:[]},addEventListener(){}};
 const context={window,document,navigator:{onLine:online},location:{hash:'#page='+page,protocol:'http:',href:'http://test/'},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},URLSearchParams,URL,AbortController,Date,setInterval(){},setTimeout(){},clearTimeout(){},console,
 fetch:async url=>{if(url==='data/sites.json')return {ok:true,json:async()=>sites};calls.push(url);const today=new Date().toISOString().slice(0,10);return {ok:true,json:async()=>({timezone:'UTC',utc_offset_seconds:0,daily_units:{precipitation_sum:'mm',temperature_2m_max:'°C'},daily:{time:Array.from({length:8},(_,i)=>O.add(today,i)),precipitation_sum:Array(8).fill(rain),temperature_2m_max:Array(8).fill(heat)}})};}};
 vm.createContext(context);await vm.runInContext(fs.readFileSync(require.resolve('../assets/field-app.js'),'utf8'),context);for(let i=0;i<30;i++)await new Promise(resolve=>setImmediate(resolve));return {calls,html:nodes.app.innerHTML,store};
}
test('first-open automatically fetches 21 groups and paints completed network without a click',async()=>{const b=await boot();assert.equal(b.calls.length,21);assert.ok(b.html.includes('21/21'));assert.ok(b.html.includes('Finished 21 / 21 groups'));});
test('fresh cached network is shown immediately without another API batch',async()=>{const b=await boot({cached:Array.from({length:21},(_,i)=>forecast(i))});assert.equal(b.calls.length,0);assert.ok(b.html.includes('21/21'));assert.ok(b.html.includes('7-day heavy rain: Red'));});
test('offline first-open explains unavailable data and does not make network forecast requests',async()=>{const b=await boot({online:false});assert.equal(b.calls.length,0);assert.ok(b.html.includes('Offline · showing saved forecasts'));assert.ok(b.html.includes('awaiting forecasts'));});

test('clear city card names no arbitrary hazard and incomplete groups remain visible',()=>{const n=forecast();n.windows[7].levels={rain:'green',heat:'green',dry:'green',compound:'green'};const s=D.citySummary([{n,current:true},{n:null,current:false}],7);assert.equal(s.line,'No alerts in 1/2 groups');assert.ok(s.detail.includes('1 unavailable'));});
test('situation headline follows current alerts and reports a window rather than invented onset',()=>{const n=forecast();const groups=[{site:{cityName:'Coimbra'},n,current:true},{site:{cityName:'Oslo'},n:forecast(1),current:false}];const s=D.situation(groups,7);assert.equal(s.headline,'Coimbra: 7-day heavy rain Red alert · 30 Sep–6 Oct');assert.equal(s.summary,'Oslo: awaiting current forecasts');groups[0].current=false;assert.equal(D.situation(groups,7).headline,'Awaiting current weather forecasts');});
test('Mission control derives fresh suggestions on open without accepting a plan',async()=>{const network=await boot({rain:100,heat:35});const cached=JSON.parse(network.store['streamsignal.groupForecasts.v6']);const mission=await boot({cached,page:'mission'});assert.equal(mission.calls.length,0);assert.ok(mission.html.includes('data-field="accept-suggestions" >'));assert.ok(!mission.html.includes('No eligible fresh alerts'));assert.equal(mission.store['streamsignal.plan.v5'],undefined);for(const n of cached)n.retrievedAt='2020-01-01T00:00:00Z';const stale=await boot({cached,page:'mission'});assert.ok(stale.html.includes('No eligible fresh alerts'));assert.ok(stale.html.includes('data-field="accept-suggestions" disabled'));});
