const test=require('node:test'),assert=require('node:assert/strict'),N=require('../assets/nwp.js'),O=require('../assets/operations-core.js'),L=require('../assets/live-core.js'),sites=require('../data/sites.json');
const now='2026-09-29T17:00:00Z',site=sites.find(s=>s.code==='C2');
function raw(){return {timezone:'Europe/Lisbon',utc_offset_seconds:3600,latitude:40.2,longitude:-8.4,daily_units:{precipitation_sum:'mm',temperature_2m_max:'°C'},daily:{time:Array.from({length:8},(_,i)=>O.add('2026-09-29',i)),precipitation_sum:[0,1,0,2,6,5,15,6],temperature_2m_max:[25,23,24,29,24,25,21,21]}};}
function fixture(g=site.group){const s=sites.find(s=>s.group===g),n=N.processAll(raw(),s,now);for(const w of Object.values(n.windows))w.levels={rain:'yellow',heat:'green'};return n;}
test('seven-day calibrated features use all seven local dates and retain exact policy/model provenance',()=>{const n=N.processAll(raw(),site,now);assert.equal(n.windows[7].start,'2026-09-30');assert.equal(n.windows[7].end,'2026-10-06');assert.equal(n.windows[7].rainTotal,35);assert.deepEqual(n.windows[7].features.rain,[Math.log1p(35),Math.log1p(15)]);assert.equal(n.windows[3].rainTotal,3);assert.equal(n.extendedParameterSha256,N.data.multiSha256);assert.equal(n.windows[7].policies.rain.selectionPeriod,'2025');assert.equal(n.windows[7].policies.rain.fitPeriod,'2024');assert.equal(n.windows[7].policies.rain.yellow,.14);assert.equal(n.windows[7].policies.rain.red,.35);});
test('partial seven-day data does not invalidate complete three-day probabilities or create a false seven-day green',()=>{const r=raw();r.daily.precipitation_sum[7]=null;const n=N.processAll(r,site,now);assert.ok(Number.isFinite(n.windows[3].probabilities.rain));assert.ok(n.windows[7].error);assert.equal(n.windows[7].levels,undefined);assert.equal(N.policyLevel(null,{yellow:.2,red:.4}),'unknown');assert.equal(N.policyLevel(.95,{yellow:.2,red:null}),'yellow');});
test('recommendations use distinct fresh current-version groups and rank site background within a group',()=>{const groups=[...new Set(sites.map(s=>s.group))].slice(0,8),forecasts=groups.map(fixture),opts={now:Date.parse(now),version:N.currentVersion()};const plan=O.recommend(sites,forecasts,opts);assert.equal(plan.length,5);assert.equal(new Set(plan.map(p=>p.site.group)).size,5);for(const p of plan){const ranks=sites.filter(s=>s.group===p.site.group).map(s=>O.context(s,sites,now.slice(0,10)).score);assert.equal(p.background.score,Math.max(...ranks));assert.equal(p.start,O.add(p.anchor,1));assert.equal(p.end,O.add(p.anchor,2));}assert.equal(O.recommend(sites,forecasts,{...opts,now:Date.parse(now)+21600001}).length,0);assert.equal(O.recommend(sites,forecasts,{...opts,version:'different-model'}).length,0);});
test('all-green, empty, future and city-filtered forecasts never fabricate visits',()=>{const n=fixture();for(const w of Object.values(n.windows))w.levels={rain:'green',heat:'green'};const opts={now:Date.parse(now),version:N.currentVersion()};assert.equal(O.recommend(sites,[n],opts).length,0);assert.equal(O.recommend(sites,[],opts).length,0);assert.equal(O.recommend(sites,[fixture()],{...opts,city:'Benevento'}).length,0);assert.equal(O.status({...n,retrievedAt:'2026-09-30T00:00:00Z'},Date.parse(now),N.currentVersion()),'stale');});
test('missing context and future samples remain explicit rather than fabricated current risk',()=>{const s={code:'X',cityName:'Test',context:{health:[{date:'2027-01-01',fecal:1}]}};const c=O.context(s,[s],'2026-09-29');assert.equal(c.coverage,0);assert.equal(c.healthDate,null);assert.ok(c.reasons.some(r=>r.includes('Missing')));});
test('ICS uses tentative all-day windows, exclusive end dates, CRLF and byte-safe line folding',()=>{const plan=O.recommend(sites,[fixture()],{now:Date.parse(now),version:N.currentVersion()});assert.equal(plan.length,1);plan[0].site={...plan[0].site,name:'A; B, C\\D\nInjected: text '+('é'.repeat(120))};const text=O.calendar(plan,now);assert.ok(text.includes('STATUS:TENTATIVE'));assert.ok(text.includes('DTEND;VALUE=DATE:'+plan[0].calendarEndExclusive.replaceAll('-','')));assert.ok(!text.includes('ATTENDEE:'));assert.ok(!text.includes('METHOD:REQUEST'));for(const line of text.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);assert.ok(text.includes('A\\; B\\, C\\\\D\\nInjected:'));});
test('print brief escapes site text and records probabilities, windows and provenance',()=>{const plan=O.recommend(sites,[fixture()],{now:Date.parse(now),version:N.currentVersion()});plan[0].site={...plan[0].site,name:'<img src=x onerror=alert(1)>'};const html=O.brief(plan,now);assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('&lt;img'));assert.ok(html.includes(plan[0].forecast.retrievedAt));assert.ok(html.includes('@page{size:A4'));});
test('forecast/field pairing compares observation dates in forecast local time',()=>{const f={id:'local',site:'C2',start:'2026-09-30',end:'2026-10-06',timezone:'Europe/Lisbon',retrievedAt:now};const r={site:'C2',date:'2026-09-29',observedAt:'2026-09-29T23:30:00Z',recordType:'Actual observation'};assert.equal(L.match(r,[f]).id,'local');assert.equal(L.match({...r,observedAt:'2026-09-29T20:00:00Z'},[f]),null);});
test('sampling suggestions respect the selected alert horizon',()=>{const n=fixture();n.windows[3].levels={rain:'green',heat:'green'};const opts={now:Date.parse(now),version:N.currentVersion()};assert.equal(O.recommend(sites,[n],{...opts,horizon:3}).length,0);assert.equal(O.recommend(sites,[n],{...opts,horizon:7}).length,1);});
